### ISSUE TITLE
Ripper not starting due to an error.

### ISSUE THREAD

**Issue by CaylenFox** [lauhayden/musedash-ripper#1]
Hey Hayden, when I start the ripper as of 1-29-2024 I get an error message. If you are still working on this project I just wanted to reach out as I enjoy Muse Dash's music.
![image_2024-01-29_114850323](https://github.com/lauhayden/musedash-ripper/assets/158078577/1985ac79-9778-46df-87bd-9e0f53717558)
Thanks again for your work on this project.

**Comment by lauhayden** [comment]
Hmmm I'll take a look when I have time, thanks for reporting the issue.

**Comment by CaylenFox** [comment]
Happy to help, have a great day.

**Comment by lauhayden** [comment]
Released [v1.3.0](https://github.com/lauhayden/musedash-ripper/releases/tag/v1.3.0) which fixes the issue.
